services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: wireguard-pg:devcontainer
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/zsh -c "while sleep 1000; do :; done"
    network_mode: bridge
    user: dev

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 9080:9080
    depends_on:
      - db
    # security_opt:
    #   - seccomp:unconfined
    # environment:
    #   DATABASE_URL: "postgresql://dbuser:test@db:5432/devdb"

  db:
    image: postgres:13
    # user: 1000:1000
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: test
      POSTGRES_DB: devdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9085:8080

volumes:
  db-data:
